Update triger.yml

diff --git a/.github/workflows/triger.yml b/.github/workflows/triger.yml
--- a/.github/workflows/triger.yml
+++ b/.github/workflows/triger.yml
@@ -9,4 +9,32 @@ jobs:
     steps:
     - name: Validate test
       run: |
-        curl -X POST https://services.beta.wincan.com/jenkins/job/Trigger/buildWithParameters?GITHUB_SHA=${{ github.sha }} -u 1ee7add0-4e4d-4c7a-93aa-fd406898e323:111791b18b6defe4c10e212aab02300f00 -k
+        $BRANCH_NAME = "${{ github.ref }}".Split("/")[-1]
+        $url = "https://services.beta.wincan.com/jenkins/job/st/buildWithParameters?token=12345&cause=Triggered+by+GitHub+Actions&BranchName=" + $BRANCH_NAME
+        JENKINS_QUEUE_ITEM=$(curl -X POST $url -u kolko:${{secrets.JENKINSACCESS}} -k)
+        echo "JENKINS_QUEUE_ITEM=${JENKINS_QUEUE_ITEM}" >> $GITHUB_ENV
+
+    - name: Wait for Jenkins Job to Complete
+      run: |
+        # Use a loop to periodically check the status of the Jenkins job
+        # You will need to adjust this loop based on how you're checking the job status
+        # The loop should continue until the job is complete
+        # Use the stored queue item number or build URL to check the job status
+        # Set an exit code based on the job's success or failure
+        JENKINS_JOB_STATUS="UNKNOWN"
+        while [[ "$JENKINS_JOB_STATUS" == "UNKNOWN" ]]; do
+          sleep 60  # Adjust the sleep duration as needed
+          JENKINS_JOB_STATUS=$(curl "https://services.beta.wincan.com/jenkins/job/st/api/json?tree=builds[result]" -u kolko:${{secrets.JENKINSACCESS}} | jq -r '.builds[0].result')
+          if [[ "$JENKINS_JOB_STATUS" == "null" ]]; then
+            JENKINS_JOB_STATUS="UNKNOWN"
+          fi
+        done
+
+        if [[ "$JENKINS_JOB_STATUS" != "SUCCESS" ]]; then
+          echo "Jenkins job failed"
+          exit 1
+        fi
+
+    - name: Job Succeeded
+      if: success()
+      run: echo "Jenkins job completed successfully."      
